version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: ["npm", "start"]
    ports:
      - "3000:3000"
